FROM jjanzic/docker-python3-opencv
RUN pip install opencv-contrib-python pyyaml sk-video
RUN apt-cache search ffmpeg | grep "ffmpeg"
RUN apt-get update && \
         apt-get install -y \
         libavcodec-dev libavutil-dev libavresample-dev libav-tools ffprobe


# FROM python:3.6
# # Credits https://github.com/janza/docker-python3-opencv/blob/master/Dockerfile
#
# RUN apt-get update && \
#         apt-get install -y \
#         build-essential \
#         cmake \
#         git \
#         wget \
#         unzip \
#         yasm \
#         pkg-config \
#         libswscale-dev \
#         libtbb2 \
#         libtbb-dev \
#         libjpeg-dev \
#         libpng-dev \
#         libtiff-dev \
#         libjasper-dev \
#         libavformat-dev \
#         libpq-dev
#
# RUN pip install numpy opencv-contrib-python pyyaml
#
# WORKDIR /
# RUN wget https://github.com/opencv/opencv/archive/3.3.1.zip \
# && unzip 3.3.1.zip \
# && mkdir /opencv-3.3.1/cmake_binary \
# && cd /opencv-3.3.1/cmake_binary \
# && cmake -DBUILD_TIFF=ON \
#   -D BUILD_opencv_java=OFF \
#   -D WITH_CUDA=OFF \
#   -D ENABLE_AVX=ON \
#   -D WITH_OPENGL=ON \
#   -D WITH_OPENCL=ON \
#   -D WITH_IPP=ON \
#   -D WITH_TBB=ON \
#   -D WITH_EIGEN=ON \
#   -D WITH_V4L=ON \
#   -D WITH_FFMPEG=1 \
#   -D BUILD_TESTS=OFF \
#   -D BUILD_PERF_TESTS=OFF \
#   -D CMAKE_BUILD_TYPE=RELEASE \
#   -D CMAKE_INSTALL_PREFIX=$(python3.6 -c "import sys; print(sys.prefix)") \
#   -D PYTHON_EXECUTABLE=$(which python3.6) \
#   -D PYTHON_INCLUDE_DIR=$(python3.6 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
#   -D PYTHON_PACKAGES_PATH=$(python3.6 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") .. \
# && make install \
# && rm /3.3.1.zip \
# && rm -r /opencv-3.3.1